# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/TDC/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-11244-ALESI1009/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/TDC/Desktop/TDC/project_30/project_30.cache/wt [current_project]
set_property parent.project_path C:/Users/TDC/Desktop/TDC/project_30/project_30.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/TDC/Desktop/TDC/project_30/project_30.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_28/project_28.srcs/sources_1/new/CONT_UNIT_0.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_17/project_17.srcs/sources_1/new/COUNTER_N_bits.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_26/project_26.srcs/sources_1/new/DATA_PATH_0.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/new/DIDACOMP.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_08/project_08.srcs/sources_1/new/DISP7SEG.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/new/DISP8ON.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_15/project_15.srcs/sources_1/new/EDGE_DETECTOR_00.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_27/project_27.srcs/sources_1/new/EdgeDetector_Debounce.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_07/project_07.srcs/sources_1/new/MUX4.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/imports/TDC/project_20/project_20.srcs/sources_1/new/PRESCALER_1Hz.vhd
  C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/sources_1/new/DIDACOMP_Nexys4.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/constrs_1/imports/project_30/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/TDC/Desktop/TDC/project_30/project_30.srcs/constrs_1/imports/project_30/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DIDACOMP_Nexys4 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DIDACOMP_Nexys4.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DIDACOMP_Nexys4_utilization_synth.rpt -pb DIDACOMP_Nexys4_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
